'use client';
import {useEffect,useState,FormEvent} from 'react';import Link from 'next/link';import {useCart} from '@/features/cart';
export function CheckoutForm(){const {items,subtotal,clearCart}=useCart();const [user,setUser]=useState<any>(undefined),[clients,setClients]=useState<any[]>([]),[data,setData]=useState<any>({paymentStatus:'Sin pago',delivery:'Delivery'}),[installments,setInstallments]=useState<any[]>([{amount:'',date:''}]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState('');
 useEffect(()=>{let active=true;fetch('/api/auth/me').then(r=>r.json()).then(async d=>{if(!active)return;setUser(d.user);if(d.user&&d.user.role!=='cliente'){const r=await fetch('/api/users');const v=await r.json();if(active)setClients((v.users||[]).filter((u:any)=>u.role==='cliente'));}}).catch(()=>{if(active)setUser(null);});return()=>{active=false;};},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,installments:data.paymentStatus==='En cuotas'?installments:[],items:items.map(i=>({productId:i.product.id,quantity:i.quantity}))})});const result=await r.json();if(!r.ok)throw Error(result.error);if(!result.stored)throw Error('No se guardó el pedido.');clearCart();setDone(result.orderId);}catch(e:any){setError(e.message||'Error de conexión.');}finally{setBusy(false);}}
 if(done)return <section className="cayo-card"><h2>Pedido registrado: {done}</h2><Link className="btn" href="/mis-pedidos">Ver mis pedidos</Link></section>;
 if(user===undefined)return <p>Cargando cuenta…</p>;if(!user)return <section className="cayo-card"><p>Inicia sesión para guardar el pedido.</p><Link href="/login" className="btn">Iniciar sesión</Link></section>;
 if(!items.length)return <section className="cayo-card"><p>Tu carrito está vacío.</p><Link href="/productos">Ver productos</Link></section>;
 const field=(key:string,label:string,required=true)=><label key={key}>{label}<input value={data[key]||''} required={required} onChange={e=>setData({...data,[key]:e.target.value})}/></label>;
 return <form className="cayo-form" onSubmit={submit}><h2>Datos del pedido</h2><p>{user.names} · Subtotal: S/ {subtotal.toFixed(2)}</p>{user.role!=='cliente'?<label>Cliente<select required value={data.customerId||''} onChange={e=>setData({...data,customerId:e.target.value})}><option value="">Selecciona un cliente</option>{clients.map(u=><option key={u.id} value={u.id}>{u.names} {u.surnames}</option>)}</select></label>:null}<div className="form-grid">{field('department','Departamento')}{field('province','Provincia')}{field('district','Distrito')}{field('address','Dirección')}<label>Forma de entrega<select value={data.delivery} onChange={e=>setData({...data,delivery:e.target.value})}><option>Delivery</option><option>Recojo en tienda</option></select></label><label>Estado de pago<select value={data.paymentStatus} onChange={e=>setData({...data,paymentStatus:e.target.value})}><option>Sin pago</option><option>En cuotas</option><option>Pago confirmado</option></select></label></div>{data.paymentStatus==='En cuotas'?<><h3>Cuotas</h3>{installments.map((v,index)=><div className="form-grid" key={index}><label>Monto S/<input type="number" min="0.01" step="0.01" required value={v.amount} onChange={e=>setInstallments(installments.map((k,i)=>i===index?{...k,amount:e.target.value}:k))}/></label><label>Fecha<input type="date" required value={v.date} onChange={e=>setInstallments(installments.map((k,i)=>i===index?{...k,date:e.target.value}:k))}/></label><button type="button" onClick={()=>setInstallments(installments.filter((_,i)=>i!==index))}>Quitar cuota</button></div>)}<button type="button" onClick={()=>setInstallments([...installments,{amount:'',date:''}])}>Agregar cuota</button><p>La suma debe coincidir con el total después del descuento.</p></>:null}{field('codes','Códigos guardados, separados por comas',false)}<p>Guarda los códigos en <Link href="/descuentos">Mis descuentos</Link>. El máximo acumulado es el 20%.</p>{field('notes','Notas adicionales',false)}{error?<p className="form-error" role="alert">{error}</p>:null}<button className="btn" disabled={busy}>{busy?'Guardando…':'Registrar pedido'}</button></form>;
}
