const {test,after}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const folder=fs.mkdtempSync(path.join(os.tmpdir(),'cayo-tests-'));process.env.SQLITE_FILE=path.join(folder,'test.sqlite');const app=require('../src/server/engine.cjs');
after(()=>{if(globalThis.__cayoDB)globalThis.__cayoDB.close();/* Retain the temporary database for inspection; it contains only test fixtures. */});
const p=(email,role='cliente')=>({names:'Johan',surnames:'Cojal Valle',birthDate:'1995-04-10',gender:'Masculino',phone:'+51999111222',email,password:'Prueba123',role,employeeCode:role==='cliente'?null:email});
const product=(name='Martillo')=>({name,sku:name.toUpperCase(),cat:'Herramientas',brand:'Marca',description:'Herramienta de prueba',price:100,priceUsd:30,stock:10,images:['/test.jpg'],specs:{Material:'Acero'},weight:1,dimensions:'20 x 5 cm',warranty:'Un año'});
test('Integración relacional, usuarios, sesiones, inventario y pedidos',async t=>{
 await app.setup(p('admin@test.local','admin'),[]);const admin=(await app.login({email:'admin@test.local',password:'Prueba123'})).user;
 let client,other,seller,pid,orderId;
 await t.test('validaciones personales y contraseñas',async()=>{
  for(const b of [{names:'Jo'},{names:'Johan2'},{surnames:'A'},{birthDate:'2026-01-01'},{birthDate:'2020-02-31'},{gender:'Otro'},{phone:'999111222'},{email:'mal'},{password:'abc'},{password:'abcdefg'},{password:'ABCDEF'},{employeeCode:''}]){
   const input={...p('invalid@test.local'),...b};if('employeeCode' in b)assert.throws(()=>app.person(input,'vendedor'));else await assert.rejects(app.register(input));}
 });
 await t.test('registro impide escalación de rol y duplicados',async()=>{client=await app.register({...p('cliente@test.local'),role:'admin'});assert.equal(client.role,'cliente');other=await app.register(p('otro@test.local'));seller=await app.register(p('vendedor@test.local','vendedor'),admin);await assert.rejects(app.register(p('cliente@test.local')),/registrado/);assert.equal((await app.users(seller)).length,2);assert.equal((await app.users(admin,'vendedor')).length,1);await assert.rejects(app.users(client),/autorizado/);});
 await t.test('login, expiración, logout y hash seguro',async()=>{await assert.rejects(app.login({email:client.email,password:'mala'}),/incorrectos/);const s=await app.login({email:client.email,password:'Prueba123'});assert.equal((await app.session(s.token)).id,client.id);assert.equal(await app.session('no-valido'),null);assert.equal(await app.session(null),null);const db=await app.database();const saved=app.one(db,'SELECT password_hash FROM users WHERE id=?',[client.id]);assert.match(saved.password_hash,/^\$2/);assert.notEqual(saved.password_hash,'Prueba123');await app.logout(s.token,client);assert.equal(await app.session(s.token),null);});
 await t.test('gestión de productos persiste y sincroniza catálogo',async()=>{await assert.rejects(app.saveProduct(product(),client),/autorizado/);pid=(await app.saveProduct(product(),admin)).id;let row=(await app.products()).find(v=>v.id===pid);assert.equal(row.priceUsd,30);assert.equal(row.stock,10);await app.saveProduct({...row,brand:'Nueva marca'},admin,pid);assert.equal((await app.products()).find(v=>v.id===pid).brand,'Nueva marca');await assert.rejects(app.saveProduct(product(),admin),/existe/);await assert.rejects(app.saveProduct({...product('Otro'),stock:1.5},admin),/entero/);await assert.rejects(app.saveProduct({...product('Otro'),images:['javascript:alert(1)']},admin),/imágenes/);await assert.rejects(app.saveProduct({...product('Otro'),specs:'invalid'},admin),/JSON/);});
 let did;
 await t.test('gestión y guardado de descuentos',async()=>{await assert.rejects(app.saveDiscount({code:'corto'},admin),/12/);did=(await app.saveDiscount({code:'DESCUENTCAYO',description:'Descuento para clientes.',type:'Porcentaje',value:40},admin)).id;await app.saveDiscount({code:'DESCUENTCAYO',description:'Descuento para clientes.',type:'Porcentaje',value:30},admin,did);await assert.rejects(app.collectDiscount('NOEXISTE',client),/válido/);await app.collectDiscount('DESCUENTCAYO',client);assert.equal((await app.discounts(client))[0].saved,1);await assert.rejects(app.saveDiscount({code:'ABCDEFGHIJKL',description:'Oferta 12345',type:'Monto fijo',value:5},admin),/letras/);});
 const body=()=>({department:'Lima',province:'Lima',district:'Surco',address:'Av. Prueba 123',paymentStatus:'Sin pago',items:[{productId:pid,quantity:1}],codes:['DESCUENTCAYO']});
 await t.test('pedido suma productos duplicados y limita descuento al 20%',async()=>{const result=await app.createOrder({...body(),items:[{productId:pid,quantity:1},{productId:pid,quantity:1}]},client);orderId=result.orderId;assert.equal(result.stored,true);const detail=await app.orderDetail(client,orderId);assert.equal(detail.subtotal,200);assert.equal(detail.total,160);assert.equal(detail.items.length,1);assert.equal(detail.items[0].quantity,2);assert.equal((await app.products()).find(v=>v.id===pid).stock,8);});
 await t.test('permisos de propiedad y filtros de pedidos',async()=>{await assert.rejects(app.orderDetail(other,orderId),/autorizado/);assert.equal((await app.orders(other,{q:'Martillo'})).length,0);assert.equal((await app.orders(seller)).length,0);assert.equal((await app.orders(client,{q:'Martillo',payment:'Sin pago'})).length,1);assert.equal((await app.orders(client,{status:'Entregado'})).length,0);assert.equal((await app.orders(admin,{date:new Date().toISOString().slice(0,10)})).length,1);await assert.rejects(app.orders(null),/sesión/);});
 await t.test('stock insuficiente y errores revierten toda la transacción',async()=>{const before=(await app.products()).find(v=>v.id===pid).stock;await assert.rejects(app.createOrder({...body(),items:[{productId:pid,quantity:9}]},client),/Stock/);assert.equal((await app.products()).find(v=>v.id===pid).stock,before);assert.equal((await app.orders(client)).length,1);await assert.rejects(app.createOrder({...body(),items:[]},client),/productos/);await assert.rejects(app.createOrder({...body(),items:[{productId:'missing',quantity:1}]},client),/disponible/);await assert.rejects(app.createOrder({...body(),codes:['INEXISTENTE']},client),/inválido/);});
 await t.test('actualización conserva precios y ajusta inventario',async()=>{const row=(await app.products()).find(v=>v.id===pid);await app.saveProduct({...row,price:150},admin,pid);await app.updateOrder({items:[{productId:pid,quantity:3}],paymentStatus:'Pago confirmado',notes:'Actualizado'},client,orderId);const o=await app.orderDetail(client,orderId);assert.equal(o.items[0].price,100);assert.equal(o.total,240);assert.equal((await app.products()).find(v=>v.id===pid).stock,7);assert.equal(o.notes,'Actualizado');});
 await t.test('cancelar devuelve stock una vez y bloquea cambios',async()=>{await app.updateOrder({},client,orderId,true);assert.equal((await app.products()).find(v=>v.id===pid).stock,10);await assert.rejects(app.updateOrder({},client,orderId,true),/Solo/);await assert.rejects(app.updateOrder({items:[{productId:pid,quantity:1}]},client,orderId),/Solo/);assert.equal((await app.products()).find(v=>v.id===pid).stock,10);});
 await t.test('cuotas deben cubrir el total y se guardan',async()=>{await assert.rejects(app.createOrder({...body(),paymentStatus:'En cuotas',installments:{}},client),/Cuotas/);await assert.rejects(app.createOrder({...body(),paymentStatus:'En cuotas',installments:[{amount:120,date:'2027-02-31'}]},client),/inválida/);await assert.rejects(app.createOrder({...body(),paymentStatus:'En cuotas',installments:[{amount:5,date:'2027-01-01'}]},client),/sumar/);const r=await app.createOrder({...body(),paymentStatus:'En cuotas',installments:[{amount:60,date:'2027-01-01'},{amount:60,date:'2027-02-01'}]},client);const o=await app.orderDetail(client,r.orderId);assert.equal(o.total,120);assert.equal(o.installments.length,2);await app.updateOrder({deliveryStatus:'Preparando envío'},admin,r.orderId);await assert.rejects(app.updateOrder({},client,r.orderId,true),/Solo/);await app.updateOrder({deliveryStatus:'Enviado'},admin,r.orderId);await app.updateOrder({deliveryStatus:'Entregado'},admin,r.orderId);});
 await t.test('vendedor registra y gestiona únicamente pedidos propios',async()=>{const r=await app.createOrder({...body(),customerId:other.id,codes:[]},seller);const o=await app.orderDetail(seller,r.orderId);assert.equal(o.seller.id,seller.id);assert.equal((await app.orders(seller)).length,1);await assert.rejects(app.updateOrder({deliveryStatus:'Preparando envío'},seller,r.orderId),/Confirma/);await assert.rejects(app.updateOrder({deliveryStatus:'Enviado'},seller,r.orderId),/Transición/);await assert.rejects(app.updateOrder({deliveryStatus:'Preparando envío'},other,r.orderId),/autorizado/);});
 await t.test('restricciones al editar clientes y eliminar usuarios',async()=>{await assert.rejects(app.updateUser(p(client.email),admin,client.id),/pedidos/);const unused=await app.register(p('sinpedidos@test.local'));await app.updateUser({...p('editado@test.local'),names:'Carlos'},admin,unused.id);assert.equal((await app.users(admin,'editado'))[0].names,'Carlos');await assert.rejects(app.updateUser({},admin,admin.id,true),/propia/);await app.updateUser({},admin,unused.id,true);assert.equal((await app.users(admin,'editado')).length,0);});
 await t.test('cambio de contraseña requiere actual o permiso y revoca sesiones',async()=>{const s=await app.login({email:client.email,password:'Prueba123'});await assert.rejects(app.changePassword({currentPassword:'mala',newPassword:'Nueva123',confirmPassword:'Nueva123'},client),/actual/);await assert.rejects(app.changePassword({newPassword:'Nueva123',confirmPassword:'Nueva123'},seller,admin.id),/clientes/);await assert.rejects(app.changePassword({currentPassword:'Prueba123',newPassword:'Nueva123',confirmPassword:'otra'},client),/coinciden/);await app.changePassword({newPassword:'Nueva123',confirmPassword:'Nueva123'},seller,client.id);assert.equal(await app.session(s.token),null);assert.equal((await app.login({email:client.email,password:'Nueva123'})).user.id,client.id);});
 await t.test('retiro de productos y descuentos conserva historial',async()=>{await app.saveProduct({},admin,pid,true);assert.equal((await app.products()).length,0);assert.equal((await app.products(true)).length,1);assert.equal((await app.orderDetail(client,orderId)).items[0].name,'Martillo');await app.saveDiscount({},admin,did,true);assert.equal((await app.discounts(client)).length,0);assert.equal((await app.discounts(admin))[0].active,0);});
 await t.test('archivo SQLite, claves foráneas, auditoría y respaldo',async()=>{const bytes=fs.readFileSync(app.filename());assert.equal(bytes.subarray(0,15).toString(),'SQLite format 3');const db=await app.database();assert.equal(app.one(db,'PRAGMA foreign_keys').foreign_keys,1);assert.ok(Number(app.one(db,'SELECT COUNT(*) n FROM audit_log').n)>10);assert.ok(fs.readdirSync(path.join(folder,'backups')).some(f=>f.endsWith('.sqlite')));const copy=new globalThis.__cayoSQL.Database(bytes);assert.equal(app.one(copy,'SELECT COUNT(*) n FROM orders').n,3);copy.close();});
});
