'use client';
import {useEffect,useState,FormEvent} from 'react';
const blank={code:'',description:'',type:'Porcentaje',value:'',active:true};
export function DiscountManager({admin=false}:{admin?:boolean}){const [rows,setRows]=useState<any[]>([]),[draft,setDraft]=useState<any>({...blank}),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false);
 async function load(q=''){try{const r=await fetch('/api/discounts?q='+encodeURIComponent(q));const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.discounts);}catch(e:any){setMessage(e.message);}}
 useEffect(()=>{load();},[]);
 async function send(method:string,body:any,did?:string){const r=await fetch('/api/discounts'+(did?'?id='+encodeURIComponent(did):''),{method,headers:{'Content-Type':'application/json'},...(method!=='DELETE'?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error);await load(query);}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{await send(draft.id?'PATCH':'POST',draft);setDraft({...blank});setMessage('Descuento guardado.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 async function collect(value:string){try{await send('POST',{collect:true,code:value});setCode('');setMessage('Código guardado para tus pedidos.');}catch(e:any){setMessage(e.message);}}
 async function remove(d:any){if(!confirm('¿Retirar el código '+d.code+'?'))return;try{await send('DELETE',{},d.id);}catch(e:any){setMessage(e.message);}}
 return <section className="cayo-card"><h2>{admin?'Administrar descuentos':'Mis descuentos'}</h2><p>Los descuentos acumulados se limitan al 20% del subtotal.</p><p role="status">{message}</p><form className="form-grid" onSubmit={e=>{e.preventDefault();load(query);}}><label>Buscar<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="btn">Buscar</button></form>{admin?<form className="cayo-form" onSubmit={save}><h3>{draft.id?'Editar descuento':'Crear descuento'}</h3><label>Código (12 letras mayúsculas)<input required pattern="[A-Z]{12}" maxLength={12} value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value.toUpperCase()})}/></label><label>Descripción<textarea required minLength={10} maxLength={200} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Tipo<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}><option>Porcentaje</option><option>Monto fijo</option></select></label><label>Valor<input type="number" min="0.01" step="0.01" required value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={!!draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>Activo</label><button className="btn" disabled={busy}>Guardar</button><button type="button" onClick={()=>setDraft({...blank})}>Nuevo / limpiar</button></form>:<form className="form-grid" onSubmit={e=>{e.preventDefault();collect(code);}}><label>Guardar código<input required value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><button className="btn">Guardar código</button></form>}<div className="table-scroll"><table><thead><tr><th>Código</th><th>Descripción</th><th>Valor</th><th>Acciones</th></tr></thead><tbody>{rows.map(d=><tr key={d.id}><td>{d.code}{!d.active?' (retirado)':''}</td><td>{d.description}</td><td>{d.type==='Porcentaje'?d.value+'%':'S/ '+Number(d.value).toFixed(2)}</td><td>{admin?<><button onClick={()=>setDraft({...d})}>Editar</button><button onClick={()=>remove(d)}>Retirar</button></>:d.saved?<span>Guardado</span>:<button onClick={()=>collect(d.code)}>Guardar código</button>}</td></tr>)}</tbody></table></div></section>;
}
