'use client';
import {FormEvent,useEffect,useState} from 'react';
const blank={name:'',sku:'',cat:'',brand:'',description:'',price:'',priceUsd:'',stock:'',images:'',specs:'',weight:'',dimensions:'',warranty:'',oldPrice:'',active:true,featured:false};
export function ProductManager(){const [rows,setRows]=useState<any[]>([]),[draft,setDraft]=useState<any>({...blank}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 async function load(){try{const r=await fetch('/api/admin/products');const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.products);}catch(e:any){setMessage(e.message);}}
 useEffect(()=>{load();},[]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/admin/products',{method:draft.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,specs:Object.fromEntries(String(draft.specs).split('\n').filter(line=>line.trim()).map(line=>{const colon=line.indexOf(':');if(colon<1||!line.slice(colon+1).trim())throw Error('Cada especificación debe tener propiedad: valor.');return [line.slice(0,colon).trim(),line.slice(colon+1).trim()];}))})});const d=await r.json();if(!r.ok)throw Error(d.error);setDraft({...blank});setMessage('Producto guardado.');await load();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 async function remove(p:any){if(!confirm('¿Retirar '+p.name+' del catálogo?'))return;try{const r=await fetch('/api/admin/products?id='+encodeURIComponent(p.id),{method:'DELETE',headers:{'Content-Type':'application/json'}});const d=await r.json();if(!r.ok)throw Error(d.error);load();}catch(e:any){setMessage(e.message);}}
 return <section className="cayo-card"><h2>Productos</h2><p role="status">{message}</p><form className="cayo-form" onSubmit={save}><h3>{draft.id?'Editar producto':'Crear producto'}</h3><div className="form-grid">{[['name','Nombre'],['sku','SKU'],['cat','Categoría'],['brand','Marca'],['price','Precio S/'],['priceUsd','Precio USD'],['stock','Stock'],['weight','Peso kg'],['dimensions','Dimensiones'],['warranty','Garantía'],['oldPrice','Precio anterior S/']].map(([key,label])=><label key={key}>{label}<input required={key!=='oldPrice'} type={['price','priceUsd','stock','weight','oldPrice'].includes(key)?'number':'text'} min="0" step={key==='stock'?'1':'0.01'} value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}</div><label>Descripción<textarea required value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Imágenes (una URL o ruta / por línea)<textarea required value={draft.images} onChange={e=>setDraft({...draft,images:e.target.value})}/></label><label>Especificaciones (una propiedad: valor por línea)<textarea value={draft.specs} onChange={e=>setDraft({...draft,specs:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>Visible en catálogo</label><label className="check-label"><input type="checkbox" checked={draft.featured} onChange={e=>setDraft({...draft,featured:e.target.checked})}/>Destacado</label><div className="button-row"><button className="btn" disabled={busy}>{busy?'Guardando…':'Guardar'}</button><button type="button" onClick={()=>setDraft({...blank})}>Nuevo / limpiar</button></div></form><label>Buscar producto<input value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="table-scroll"><table><thead><tr><th>Producto</th><th>SKU</th><th>S/</th><th>USD</th><th>Stock</th><th>Acciones</th></tr></thead><tbody>{rows.filter(p=>[p.name,p.sku,p.brand,p.cat].join(' ').toLowerCase().includes(query.toLowerCase())).map(p=><tr key={p.id}><td>{p.name}{!p.active?' (retirado)':''}</td><td>{p.sku}</td><td>{p.price.toFixed(2)}</td><td>{p.priceUsd.toFixed(2)}</td><td>{p.stock}</td><td><button onClick={()=>setDraft({...p,images:p.images.join('\n'),specs:Object.entries(p.specs).map(([k,v])=>k+': '+v).join('\n')})}>Editar</button><button onClick={()=>remove(p)}>Retirar</button></td></tr>)}</tbody></table></div></section>;
}
