'use client';
import {FormEvent,useEffect,useState} from 'react';import {PersonFields} from '@/features/account/ui/PersonFields';
export function UserManager({role}:{role:string}){const [rows,setRows]=useState<any[]>([]),[draft,setDraft]=useState<any>({role:'cliente'}),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[target,setTarget]=useState<any>(null),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState('');
 async function load(q=''){try{const r=await fetch('/api/users?q='+encodeURIComponent(q));const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.users);}catch(e:any){setMessage(e.message);}}
 useEffect(()=>{load();},[]);
 async function call(url:string,method:string,body?:any){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{await call('/api/users',draft.id?'PATCH':'POST',draft);setDraft({role:'cliente'});setMessage('Usuario guardado.');await load(query);}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 async function remove(u:any){if(!confirm('¿Eliminar a '+u.names+'?'))return;try{await call('/api/users?id='+encodeURIComponent(u.id),'DELETE');await load(query);}catch(e:any){setMessage(e.message);}}
 async function change(e:FormEvent){e.preventDefault();setBusy(true);try{await call('/api/users/'+target.id+'/password','POST',{newPassword:password,confirmPassword});setTarget(null);setPassword('');setConfirmPassword('');setMessage('Contraseña cambiada. Las sesiones del usuario fueron cerradas.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 return <section className="cayo-card"><h2>{role==='admin'?'Clientes y vendedores':'Clientes'}</h2><p role="status">{message}</p><form className="form-grid" onSubmit={e=>{e.preventDefault();load(query);}}><label>Buscar por nombre, correo o código<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="btn">Buscar</button></form><form className="cayo-form" onSubmit={save}><h3>{draft.id?'Editar usuario':'Registrar usuario'}</h3><PersonFields value={draft} onChange={setDraft} roles={role==='admin'}/>{!draft.id?<label>Contraseña<input type="password" required minLength={6} maxLength={50} value={draft.password||''} onChange={e=>setDraft({...draft,password:e.target.value})}/></label>:null}<div className="button-row"><button className="btn" disabled={busy}>Guardar</button><button type="button" onClick={()=>setDraft({role:'cliente'})}>Nuevo / limpiar</button></div></form>{target?<form className="cayo-form" onSubmit={change}><h3>Cambiar contraseña de {target.names}</h3><label>Nueva contraseña<input type="password" required minLength={6} maxLength={50} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirmación<input type="password" required value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><button className="btn" disabled={busy}>Cambiar contraseña</button><button type="button" onClick={()=>setTarget(null)}>Cerrar</button></form>:null}<div className="table-scroll"><table><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Acciones</th></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td>{u.names} {u.surnames}<details><summary>Datos</summary><p>Teléfono: {u.phone}</p><p>Nacimiento: {u.birthDate}</p><p>Género: {u.gender}</p><p>Código: {u.employeeCode||'No aplica'}</p></details></td><td>{u.email}</td><td>{u.role}</td><td>{role==='admin'?<><button onClick={()=>setDraft({...u})}>Editar</button><button onClick={()=>remove(u)}>Eliminar</button></>:null}<button onClick={()=>setTarget(u)}>Cambiar contraseña</button></td></tr>)}</tbody></table></div></section>;
}
